backend:
  name: git-gateway
  branch: main

media_folder: "assets/images" # Where media files will be stored

collections:
  - name: "posts" # A unique name for the collection
    label: "Blog Posts" # The name that appears in the admin UI
    folder: "posts" # The folder in your repo where posts are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each post
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
