
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "wallpapers"
    label: "Wallpapers"
    folder: "content/wallpapers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Nature", "Abstract", "Technology", "Animals", "Movies"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Video (optional)", name: "video", widget: "string", required: false}
